// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkiuwribklnwnlsuttgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndraXV3cmlia2xud25sc3V0dGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzUyNDEsImV4cCI6MjA3MjExMTI0MX0.AjErf8ezehVhh72sDmnQcVnLOS_aXER-0gdGPOu2uJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});